// javascript/src/components/standardComponents/standardTextBox/StandardTextBox.tsx
import React, { useEffect, useState } from "react";

import "./StandardTextbox.scss";

interface StandardTextboxProps {
  id: string,
  defaultValue?: string,
  label?: string,
  placeholder?: string
}

export default function StandardTextbox (props: StandardTextboxProps) {
  return (
    <span className="standard-textbox">
      { props.label && <label for={ props.id }>{ props.label }</label> }
      <input type="text" id={ props.id }
                         name={ props.id }
                         placeholder={ props.placeholder }
                         defaultValue={ props.defaultValue } />
    </span>
  )
}

// src/components/StandardComponents/StandardTextbox/StandardTextbox.vue
<template>
  <span class="standard-textbox">
    <label v-if="props.label" :for="props.id">{{ props.label }}</label>
    <input type="text" :id="props.id"
                       :name="props.id"
                       :placeholder="props.placeholder"
                       :defaultValue="props.defaultValue" />
  </span>
</template>

<script setup>
const props = defineProps({
  id: {
    type: String,
    default: ''
  },
  defaultValue: {
    type: String,
    default: ''
  },
  label: {
    type: String,
    default: ''
  },
  placeholder: {
    type: String,
    default: ''
  },
});
</script>

<style scoped lang="scss">
@import "./StandardTextbox.scss";
</style>
