// src/components/StandardComponents/StandardTable/StandardTable.vue
<template>
  <table class="standard-table">
    <tr>
      <th :v-for="header in props.headers" 
          :key="headerKeys[header]">{{ header }}</th>
    </tr>
    <tr :v-for="row in props.rows"
        :key="`row-${row.id}`">
        <td :v-for="header in headers"
            :key="`${headerKeys[header]}-${row.id}`">
            {{ row[headerKeys[header]] }}
        </td>
    </tr>
  </table>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  rows: {
    type: Array,
    default: []
  },
  headers: {
    type: Array,
    default: []
  }
});

const headerKeys = computed(() => {
  const headersMap = {}
  return headers.reduce(header => {
    headersMap[header] = header.toLowerCase().replace(" ", "");
    return headersMap;
  }, headersMap);
});
</script>

<style scoped lang="scss">
@import './StandardTable.scss';
</style>

// javascript/src/components/standardComponents/standardTable/StandardTable.tsx
import React from "react";
import "./StandardTable.scss";

export default function StandardTable ({rows, headers, keys}) {
  const headerRow = <tr>
    {
      headers.map(header => {
        let keyVal = header.toLowerCase().replace(" ", "");
        return <th key={`header-${keyVal}`}>{ header }</th>
      })
   }
  </tr>

  const tableBody = rows.map(row => {
    return <tr key={`row-${row.id}`}>
      {
        keys.map(key => {
          return <td key={`${key}-${row.id}`}>{ row[key] }</td>
        })
      }
    </tr>
  });

  return (
    <>
      <table className="standard-table">
        <thead>
          { headerRow }
        </thead>
        <tbody>
          { tableBody }
        </tbody>
      </table>
    </>
  );
}
