// javascript/src/components/CharacterGenerators/CharacterGeneratorRoller.tsx
import React, { useEffect, useState } from "react";

import StandardButton from "../standardComponents/standardButton/StandardButton";
import StandardDropdown from "../standardComponents/standardDropdown/StandardDropdown";

import "./CharacterGeneratorRoller.scss";
import { default as d100 } from "../../assets/d100.png";

interface CharacterGeneratorRollerProps {
  availableAncestries: Object[],
  availableClasses: Object[],
  availableGenders: Object[],
  initCharAncestry?: string,
  initCharClass?: string,
  onRoll: Function,
  onSelectAncestry: Function,
  onSelectClass: Function,
  onSelectGender: Function,
  systemName: string
}

export default function CharacterGeneratorRoller (props: CharacterGeneratorRollerProps) {
  return (
    <div className="character-generator-roller">
      <h1>
        <span>Character Roller</span>
        <span class="system-name">{ props.systemName }</span>
      </h1>
      <div className="base-options roller-options">
        <StandardDropdown placeholderText="Ancestry"
                          options={props.availableAncestries}
                          selectId="char-ancestry-dropdown"
                          onSelect={props.onSelectAncestry}
                          defaultSelectedValue={props.initCharAncestry} />
        <StandardDropdown placeholderText="Class"
                          options={props.availableClasses}
                          selectId="char-class-dropdown"
                          onSelect={props.onSelectClass}
                          defaultSelectedValue={props.initCharClass} />
        <StandardDropdown placeholderText="Name Gender"
                          options={props.availableGenders}
                          selectId="char-gender-dropdown"
                          onSelect={props.onSelectGender}/>
      </div>
      <div className="footer">
        <StandardButton onClick={props.onRoll}>
          <img src={d100} alt="Roll a character" />
        </StandardButton>
      </div>
    </div>
  )
}

// src/components/CharacterGenerators/CharacterGeneratorRoller.vue
<template>
  <div class="character-generator-roller">
    <h1>
      <span>Character Roller</span>
      <span class="system-name">{{ props.gameSystemName }}</span>
    </h1>
    <div v-if="props.loading || !props.dropdownOptions?.value">Loading...</div>
    <div class="roller-options" v-else>
      <StandardDropdown placeholderText="Name Style"
                        :options="props.dropdownOptions.value.nameStyles"
                        selectId="char-style-dropdown"
                        @select="e => $emit('setNameStyle', e)" />
      <StandardDropdown :disabled="!props.dropdownOptions.value.ancestries?.length"
                        placeholderText="Ancestry"
                        :options="props.dropdownOptions.value.ancestries"
                        selectId="char-ancestry-dropdown"
                        @select="e => $emit('setAncestry', e)" />
      <StandardDropdown placeholderText="Class"
                        :options="props.dropdownOptions.value.characterClasses"
                        selectId="char-class-dropdown"
                        @select="e => $emit('setClass', e)" />
      <StandardDropdown placeholderText="Background"
                        :options="props.dropdownOptions.value.backgrounds"
                        selectId="char-class-dropdown"
                        @select="e => $emit('setBackground', e)" />
      <StandardDropdown :disabled="!props.generatorDropdownOptions.lineages?.length"
                        placeholderText="Lineages"
                        :options="props.generatorDropdownOptions.lineages"
                        selectId="char-lineage-dropdown"
                        @select="e => $emit('setLineage', e)"
                        class="lineage-dropdown" />
      <StandardDropdown :disabled="!props.generatorDropdownOptions.characterSubclasses?.length"
                        placeholderText="Subclass"
                        :options="props.generatorDropdownOptions.characterSubclasses"
                        selectId="char-subclass-dropdown"
                        @select="e => $emit('setSubclass', e)"
                        class="subclasses-dropdown" />
      <StandardDropdown :disabled="!props.dropdownOptions.value.appearances?.length"
                        placeholderText="Appearance"
                        :options="props.dropdownOptions.value.appearances"
                        selectId="char-appearances-dropdown"
                        @select="e => $emit('setAppearance', e)"
                        class="appearances-dropdown" />
    </div>
    <div class="footer">
      <StandardButton @click="$emit('rollCharacter')">
        <img src="@/assets/d100.png" alt="Roll a character" />
      </StandardButton>
    </div>
  </div>
</template>

<script setup>
import StandardButton from "../StandardComponents/StandardButton/StandardButton";
import StandardDropdown from "../StandardComponents/StandardDropdown/StandardDropdown";
import "./CharacterGeneratorRoller.scss";

const props = defineProps({
  gameSystemName: String,
  loading: Boolean,
  dropdownOptions: Object,
  generatorDropdownOptions: Object
});
</script>
